In [78]:
import polars as pl

In [79]:
INFECTIOUS_DISEASE_DATA_AI_CLEANED_DIR = "../datasets/weekly-infectious-disease-bulletin-cases-AI-cleaned.parquet"
INFECTIOUS_DISEASE_DATA_CLEANED_DIR = "../datasets/weekly-infectious-disease-bulletin-cases-cleaned.csv"

In [80]:
df_ai_cleaned = pl.read_parquet(INFECTIOUS_DISEASE_DATA_AI_CLEANED_DIR)
df_cleaned = pl.read_csv(INFECTIOUS_DISEASE_DATA_CLEANED_DIR)

In [81]:
df_cleaned

shape: (16_066, 3)
┌──────────┬───────────────────────────────────┬──────────────┐
│ epi_week ┆ disease                           ┆ no._of_cases │
│ ---      ┆ ---                               ┆ ---          │
│ str      ┆ str                               ┆ i64          │
╞══════════╪═══════════════════════════════════╪══════════════╡
│ 2012-W01 ┆ Acute Viral hepatitis C           ┆ 0            │
│ 2012-W01 ┆ Melioidosis                       ┆ 0            │
│ 2012-W01 ┆ Poliomyelitis                     ┆ 0            │
│ 2012-W01 ┆ Salmonellosis(non-enteric fevers… ┆ 26           │
│ …        ┆ …                                 ┆ …            │
│ 2020-W52 ┆ Mumps                             ┆ 2            │
│ 2020-W53 ┆ Measles                           ┆ 0            │
│ 2020-W53 ┆ Legionellosis                     ┆ 1            │
│ 2020-W53 ┆ Acute Viral hepatitis C           ┆ 0            │
└──────────┴───────────────────────────────────┴──────────────┘

In [82]:
df_ai_cleaned

shape: (16_066, 10)
┌─────────────┬──────┬──────┬─────────────┬───┬────────────┬────────────┬─────────────┬────────────┐
│ epidemiolog ┆ year ┆ week ┆ week_start_ ┆ … ┆ case_count ┆ is_outlier ┆ transmissio ┆ burden_tie │
│ ical_week   ┆ ---  ┆ ---  ┆ date        ┆   ┆ ---        ┆ ---        ┆ n_mode      ┆ r          │
│ ---         ┆ i32  ┆ i32  ┆ ---         ┆   ┆ i64        ┆ bool       ┆ ---         ┆ ---        │
│ str         ┆      ┆      ┆ date        ┆   ┆            ┆            ┆ str         ┆ str        │
╞═════════════╪══════╪══════╪═════════════╪═══╪════════════╪════════════╪═════════════╪════════════╡
│ 2012-W01    ┆ 2012 ┆ 1    ┆ 2012-01-02  ┆ … ┆ 0          ┆ false      ┆ Other       ┆ Medium     │
│ 2012-W01    ┆ 2012 ┆ 1    ┆ 2012-01-02  ┆ … ┆ 0          ┆ false      ┆ Other       ┆ Low        │
│ 2012-W01    ┆ 2012 ┆ 1    ┆ 2012-01-02  ┆ … ┆ 0          ┆ false      ┆ Vaccine-pre ┆ Low        │
│             ┆      ┆      ┆             ┆   ┆            ┆            ┆ ventable    ┆            │
│ 2012-W01    ┆ 2012 ┆ 1    ┆ 2012-01-02  ┆ … ┆ 2          ┆ false      ┆ Vaccine-pre ┆ High       │
│             ┆      ┆      ┆             ┆   ┆            ┆            ┆ ventable    ┆            │
│ …           ┆ …    ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …           ┆ …          │
│ 2020-W53    ┆ 2020 ┆ 53   ┆ 2020-12-28  ┆ … ┆ 0          ┆ false      ┆ Respiratory ┆ Medium     │
│ 2020-W53    ┆ 2020 ┆ 53   ┆ 2020-12-28  ┆ … ┆ 0          ┆ false      ┆ Other       ┆ High       │
│ 2020-W53    ┆ 2020 ┆ 53   ┆ 2020-12-28  ┆ … ┆ 0          ┆ false      ┆ Other       ┆ Low        │
│ 2020-W53    ┆ 2020 ┆ 53   ┆ 2020-12-28  ┆ … ┆ 0          ┆ false      ┆ Vector-born ┆ Low        │
│             ┆      ┆      ┆             ┆   ┆            ┆            ┆ e           ┆            │
└─────────────┴──────┴──────┴─────────────┴───┴────────────┴────────────┴─────────────┴────────────┘

In [83]:
df_cleaned.group_by("disease").agg(pl.sum("no._of_cases")).sort("no._of_cases", descending=True)
df_ai_cleaned.group_by("disease_name").agg(pl.sum("case_count")).sort("case_count", descending=True)

shape: (42, 2)
┌───────────────────────────────────┬────────────┐
│ disease_name                      ┆ case_count │
│ ---                               ┆ ---        │
│ str                               ┆ i64        │
╞═══════════════════════════════════╪════════════╡
│ Hand, Foot and Mouth Disease      ┆ 235409     │
│ Dengue Fever                      ┆ 126642     │
│ Salmonellosis(non-enteric fevers… ┆ 16497      │
│ Mumps                             ┆ 4213       │
│ …                                 ┆ …          │
│ Poliomyelitis                     ┆ 0          │
│ Japanese Encephalitis             ┆ 0          │
│ Plague                            ┆ 0          │
│ Yellow Fever                      ┆ 0          │
└───────────────────────────────────┴────────────┘

In [84]:
df_cleaned.group_by("disease").agg(pl.sum("no._of_cases")).sort("no._of_cases", descending=True)

shape: (42, 2)
┌───────────────────────────────────┬──────────────┐
│ disease                           ┆ no._of_cases │
│ ---                               ┆ ---          │
│ str                               ┆ i64          │
╞═══════════════════════════════════╪══════════════╡
│ Hand, Foot Mouth Disease          ┆ 235409       │
│ Dengue Fever                      ┆ 126642       │
│ Salmonellosis(non-enteric fevers… ┆ 16497        │
│ Mumps                             ┆ 4213         │
│ …                                 ┆ …            │
│ Yellow Fever                      ┆ 0            │
│ Ebola Virus Disease               ┆ 0            │
│ Plague                            ┆ 0            │
│ Poliomyelitis                     ┆ 0            │
└───────────────────────────────────┴──────────────┘